services:
  - type: web
    name: book-v
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 18.20.0
      - key: VITE_API_KEY
        sync: false
        # Сюда нужно будет вставить API ключ Gemini в панели Render
